name = "NumericalRange"
uuid = "bd3c3ff1-ad01-40db-ab3f-ca12d8f2d1e9"
authors = ["Thomas Chaffey <tlc37@cam.ac.uk> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
